import React from 'react'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Background from '@/components/Background'

export default function ExploreCreators() {
  return (
    <div className='overflow-hidden w-[100%] h-[100%] bg-primary font-Raleway'>
        <Head> 
        <title>Sip&Support: Explore Creators</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <div className='flex flex-col space-y-10'>
        <Navbar />
      </div>
      
      <Background />
    </div>
  )
}
