import React from 'react'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Background from '@/components/Background'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMagnifyingGlass} from "@fortawesome/free-solid-svg-icons";
import Card from '@/components/Card';


export default function ExploreCreators() {
  return (
    <div className="overflow-hidden w-[100%] h-[100%] bg-primary font-Raleway">
      <Head>
        <title>Sip&Support: Explore Creators</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <div className="flex flex-col md:space-y-10 space-y-5 justify-center">
        <Navbar />
        <div className='flex flex-col md:space-y-20 space-y-5 items-center text-center '>
          <div className='z-20 lg:text-5xl md:text-4xl text-2xl bg-clip-text text-center text-transparent bg-gradient-to-r from-[#635AD9] to-[#88F4FF] font-bold'>Be part of an Exclusive Community</div>
        <div className='flex flex-row space-x-4 bg-secondary md:h-12 h-10 z-20 px-4 items-center rounded-lg'>
          <FontAwesomeIcon
              icon={faMagnifyingGlass}
              className="h-6 w-6 fa-heart-o justify-center items-center"
            />
          <input
              type="text"
              placeholder="Search for Creators"
              className=" bg-secondary border-none outline-none md:text-xl text-lg"
            ></input>
        </div>
        <div className='flex md:gap-10 gap-6 lg:mx-60 md:mx-20 ml-10 mt-0 overflow-auto scrollbar-width-none'>
        <Card 
        creator="Harry Styles" 
        description="s an Indian YouTuber, comedian, scriptwriter, Actor, performer and producer." 
        followers={1000} 
        image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxxe-wsaNQ49_z93ApsPfyKgD1GYBExdCubOOZGX2Q7pm0SNAyPeqIQQU20R4eiwrAmfw&usqp=CAU"
      />
      <Card 
        creator="Harry Styles" 
        description="s an Indian YouTuber, comedian, scriptwriter, Actor, performer and producer." 
        followers={1000} 
        image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxxe-wsaNQ49_z93ApsPfyKgD1GYBExdCubOOZGX2Q7pm0SNAyPeqIQQU20R4eiwrAmfw&usqp=CAU"
      />
      <Card 
        creator="Harry Styles" 
        description="s an Indian YouTuber, comedian, scriptwriter, Actor, performer and producer." 
        followers={1000} 
        image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxxe-wsaNQ49_z93ApsPfyKgD1GYBExdCubOOZGX2Q7pm0SNAyPeqIQQU20R4eiwrAmfw&usqp=CAU"
      />
        </div>
        </div>
        
      </div>

      
      
    </div>
  );
}
