import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import logo from '../public/logo.svg'
import Navbar from '@/components/Navbar'
import Background from '@/components/Background'
import Banner from '@/components/Banner'
import Card from '@/components/Card'
import { useEffect } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  return (
    <div className="overflow-hidden w-[100%] h-[100%] bg-primary font-Raleway">
      <Head>
        <title>Sip&Support</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <div className="flex flex-col space-y-10">
        <Navbar />
        <Banner />
        <div className="align-left md:text-3xl text-xl font-bold text-white lg:mx-60 md:mx-20 mx-10 md:mt-20 mt-12 mb-0 ">
          CREATORS
        </div>
        <div className="flex md:gap-10 gap-6 lg:mx-60 md:mx-20 ml-10 mt-0 overflow-auto scrollbar-width-none">
          <Card
            creator="Harry Styles"
            description="is a british singer, song-writer and actor."
            followers={3}
            image="https://media.pitchfork.com/photos/604ea63a02674855a6d5bbbb/16:9/w_4432,h_2493,c_limit/Harry-Styles.jpg"
          />
          <Card
            creator="Rashmika Mandanna"
            description="is an Indian actress who mostly works in Telugu cinema."
            followers={4}
            image="https://static.toiimg.com/photo/msid-95062045/95062045.jpg"
          />
          <Card
            creator="Taneesha Mirwani"
            description="is an Indian content creator and social media influencer."
            followers={2}
            image="https://wp.missmalini.com/wp-content/uploads/2021/02/BeFunky-collage-16-11.jpg"
          />
        </div>
      </div>
    </div>
  );
}
